config/routes.rb
Incidents::Application.routes.draw do
  

  
  resources :incidents
  

end

app/models/incident.rb
class Incident < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  # GET /incidents
  # GET /incidents.xml
  def index
    @incidents = Incident.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  {
		render :text => @incidents.to_xml(
			:root=>"data"
			)
		}
    end
  end


  
  # GET /incidents/map/1
  # GET /incidents/map/1.xml
  def show
    @incident = Incident.find(params[:id])
	respond_to do |format|
		format.html #rails call the template automatically	
		format.xml{
			render :text=>@incident.to_xml(
				:only=>[:latitude, :longitude, :title, :description],
				:root=>"data")
		}

	end
	
 end  

  # GET /incidents/new
  # GET /incidents/new.xml
  def new
    @incident = Incident.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @incident }
    end
  end

  # GET /incidents/1/edit
  def edit
    @incident = Incident.find(params[:id])
  end

  # POST /incidents
  # POST /incidents.xml
  def create
    @incident = Incident.new(params[:incident])

    respond_to do |format|
      if @incident.save
        format.html { redirect_to(@incident, :notice => 'Incident was successfully created.') }
        format.xml  { render :xml => @incident, :status => :created, :location => @incident }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /incidents/1
  # PUT /incidents/1.xml
  def update
    @incident = Incident.find(params[:id])

    respond_to do |format|
      if @incident.update_attributes(params[:incident])
        format.html { redirect_to(@incident, :notice => 'Incident was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @incident.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.xml
  def destroy
    @incident = Incident.find(params[:id])
    @incident.destroy

    respond_to do |format|
      format.html { redirect_to(incidents_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.erb
<%= form_for(@incident) do |f| %>
  <% if @incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% @incident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mountain %><br />
    <%= f.text_field :mountain %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :when %><br />
    <%= f.datetime_select :when %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incidents/_map.html.erb
<%
  google_key='ABQIAAAAnfs7bKE82qgb3Zc2YyS-oBT2yXp_' + 
    'ZAY8_ufC3CFXhHIE1NvwkxSySz_REpPq-4WZA27OwgbtyR3VcA'
  full_page ||= false
  show_action ||= nil
  new_action ||= nil
  data ||= nil
%>
<div id="map"
  align="right"
  style="border: 1px solid #979797;
		 min-width: 400px;
<%		 if full_page -%>
		 min-height: 800px;
		 height: 800px;
<%		 else -%>
		 min-height: 400px;
		 height: 400px;
<%		 end -%>
		 background-color: #FFFFFF;
		 border: 1px solid #999999;
		 padding: 10px;"></div>
<script
  src="http://maps.google.com/maps?file=api&v=2&key=<%= google_key %>"
  type="text/javascript"></script>
<script type="text/javascript">
  var map_location = new GLatLng(0, 0);
  var map;

  function show_path(id) {
    var show_path = "<%= url_for(:controller=>controller.controller_name, :action=>show_action, :id=>'REPLACEME') %>";
    return show_path.replace("REPLACEME", id);
  }

  function new_path() {
    return "<%= url_for(:controller=>controller.controller_name, :action=>new_action) %>";
  }

  function createMarker(point, label, html, id) {
    var mark1 = new GMarker(point);
    mark1.enableDragging();
    mark1.bouncy = true;
    GEvent.addListener(mark1, "click",
      function() {
        map_location = mark1.getPoint();
        map.panTo(map_location);
        var link = "";
        if (id != "") {
       <% if show_action != nil %>
            link = show_path(id);
            new Ajax.Request(link, {
              method: 'get',
              onSuccess: function(transport) {
                var html = "<div align='left' id='map_info' style='min-width: 400px; min-height: 300px; width: 400px; height: 300px;'>" +
                  transport.responseText + "</div>";
                mark1.openInfoWindowHtml(html);
              }
            });      
       <% else %>
            link = "<br/><a href='/incidents/" + id + "'>More...</a>";
            mark1.openInfoWindowHtml("<div align='left'><strong>" + label + "</strong><br/>"
              + html + link + "</div>");
       <% end %>
        } else {
          mark1.openInfoWindowHtml("<div align='left'><strong>" + label + "</strong><br/>"
            + html + link + "</div>");
        }
      }
    );
    return mark1;
  }
  
 function initialize() {
   if (GBrowserIsCompatible()) {
     map = new GMap2(document.getElementById("map"));
     map.setCenter(map_location, 16);
     map.setZoom(2);
     map.addControl(new GLargeMapControl());
     map.addControl(new GHierarchicalMapTypeControl());
     map.enableScrollWheelZoom();
     map.enableDoubleClickZoom();
     map.setMapType(G_HYBRID_MAP);
   }
 }  
  
 function textFor(element, tag) {
   return element.getElementsByTagName(tag)[0].firstChild.nodeValue;
 }

 function addPoints(points) {
   var totlat = 0.0;
   var totlon = 0.0;
   var avcount = 0;
   for (var i = 0; i < points.length; i++) {
     m = points[i];
     // obtain the attribues of each marker
     var lat = parseFloat(textFor(m, "latitude"));
     var lng = parseFloat(textFor(m, "longitude"));
     totlat = totlat + lat;
     totlon = totlon + lng;
     avcount = avcount + 1;
     var point = new GLatLng(lat,lng);
     var html = textFor(m, "description");
     var label = textFor(m, "title");
     // create the marker
     var id ="";
     if (points.length > 1) {
       id = textFor(m, "id");
     }
     var marker = createMarker(point,label,html, id);
     map.addOverlay(marker);
   }
   return new GLatLng(totlat / avcount, totlon / avcount);
 }

 function loadXml(url) {
   var request = GXmlHttp.create();
   request.open("GET", url, true);
   request.onreadystatechange = function() {
     if (request.readyState == 4) {
       var xmlDoc = GXml.parse(request.responseText);
       var points = new Array();
       points[0] = xmlDoc.documentElement;
       var multi = (points[0].getElementsByTagName("datum").length > 0);
       if (multi) {
         points=points[0].getElementsByTagName("datum");
       }
       center = addPoints(points);
       map.setCenter(center);
       if (multi) {
         map.setZoom(2);
       } else {
         map.setZoom(8);
       }
     }
   }
   request.send(null);
 }
 initialize();
<% if new_action != nil -%>
   GEvent.addListener(map, 'click',
     function(overlay, point) {
       if (point) {
         var marker = new GMarker(point);
         marker.enableDragging();
         marker.bouncy = true;
         var info = null;
         GEvent.addListener(marker, "infowindowbeforeclose",
           function() {
             info = document.getElementById("map_info");
           }
         );
         GEvent.addListener(marker, "infowindowclose",
           function() {
             if (info != null) {
               GEvent.addListener(marker, "click",
                 function() {
                 map_location = marker.getPoint();
                 map.panTo(map_location);
                 marker.openInfoWindowHtml(info);
               });
             }
           }
         );
         map.addOverlay(marker);
         var params = new Hash();
         params.set("latitude", point.y);
         params.set("longitude", point.x);
         new Ajax.Request(new_path(), {
           method: 'get',
           parameters: params,
           onSuccess: function(transport) {
             var html = "<div align='left' id='map_info' style='min-width: 400px; min-height: 300px; width: 400px; height: 300px;'>" +
               transport.responseText + "</div>";
             marker.openInfoWindowHtml(html);
           }
         });
       }
     }
   );
<% 
  end
  if (data != nil) -%>
	loadXml('<%= data -%>');
<%  end %>
</script>

app/views/incidents/edit.html.erb
<h1>Editing incident</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<h1>Listing incidents</h1>

<table>
  <tr>
    <th>Mountain</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>When</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>hey yo
  </tr>

<% @incidents.each do |incident| %>
  <tr>
    <td><%= incident.mountain %></td>
    <td><%= incident.latitude %></td>
    <td><%= incident.longitude %></td>
    <td><%= incident.when %></td>
    <td><%= incident.title %></td>
    <td><%= incident.description %></td>
    <td><%= link_to 'Show', incident %></td>
    <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
    <td><%= link_to 'Destroy', incident, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Incident', new_incident_path %>

app/views/incidents/new.html.erb
<h1>New incident</h1>

<%= render 'form' %>

<%= link_to 'Back', incidents_path %>

app/views/incidents/show.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mountain:</b>
  <%= @incident.mountain %>
</p>

<p>
  <b>Latitude:</b>
  <%= @incident.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @incident.longitude %>
</p>

<p>
  <b>When:</b>
  <%= @incident.when %>
</p>

<p>
  <b>Title:</b>
  <%= @incident.title %>
</p>

<p>
  <b>Description:</b>
  <%= @incident.description %>
</p>

<%= render :partial =>"map", :locals=>{:data=>"#{@incident.id}.xml"} %>

<%= link_to 'Edit', edit_incident_path(@incident) %> |
<%= link_to 'Back', incidents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Incidents</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>